# This file contains all available configuration options with their default values.

# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 5m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true


# all available settings of specific linters
linters-settings:
  goimports:
    local-prefixes: github.com/intellectokids-backend
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 150
  lll:
    line-length: 140

linters:
  enable:
    - govet
    - errcheck
    - ineffassign
    - typecheck
    - megacheck
    - bodyclose
    - revive
    - stylecheck
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - gocognit
    - asciicheck
    - gofmt
    - goimports
    - gomodguard
    - misspell
    - unparam
    - dogsled
    - nakedret
    - prealloc
    - gocritic
    # - gochecknoglobals
    - whitespace
    - wsl
    - goprintffuncname
    - godot
    - nolintlint
    - noctx
    - exportloopref
    - gofumpt
    - dupl
    - goheader
    - depguard
    - exhaustive
    - gomnd
    - nestif
    - predeclared
    - godot
    # - testpackage
    - nolintlint
    - noctx
    - exportloopref
    - gofumpt
    # - tparallel
    #- forbidigo
    - makezero
  fast: false
  disable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gochecknoglobals
        - wsl
        - funlen
        - goerr113
        - gofumpt
    - text: "Errors unhandled"
      linters:
        - gosec
    - linters:
        - lll
      source: "^//go:generate "
