// Code generated by MockGen. DO NOT EDIT.
// Source: check_fuel.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockICheckFuel is a mock of ICheckFuel interface.
type MockICheckFuel struct {
	ctrl     *gomock.Controller
	recorder *MockICheckFuelMockRecorder
}

// MockICheckFuelMockRecorder is the mock recorder for MockICheckFuel.
type MockICheckFuelMockRecorder struct {
	mock *MockICheckFuel
}

// NewMockICheckFuel creates a new mock instance.
func NewMockICheckFuel(ctrl *gomock.Controller) *MockICheckFuel {
	mock := &MockICheckFuel{ctrl: ctrl}
	mock.recorder = &MockICheckFuelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICheckFuel) EXPECT() *MockICheckFuelMockRecorder {
	return m.recorder
}

// GetFuel mocks base method.
func (m *MockICheckFuel) GetFuel() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFuel")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFuel indicates an expected call of GetFuel.
func (mr *MockICheckFuelMockRecorder) GetFuel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFuel", reflect.TypeOf((*MockICheckFuel)(nil).GetFuel))
}
