// Code generated by MockGen. DO NOT EDIT.
// Source: movable.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	pkg "github.com/dosovma/otus_arch/pkg"
	gomock "github.com/golang/mock/gomock"
)

// MockMovable is a mock of Movable interface.
type MockMovable struct {
	ctrl     *gomock.Controller
	recorder *MockMovableMockRecorder
}

// MockMovableMockRecorder is the mock recorder for MockMovable.
type MockMovableMockRecorder struct {
	mock *MockMovable
}

// NewMockMovable creates a new mock instance.
func NewMockMovable(ctrl *gomock.Controller) *MockMovable {
	mock := &MockMovable{ctrl: ctrl}
	mock.recorder = &MockMovableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovable) EXPECT() *MockMovableMockRecorder {
	return m.recorder
}

// GetPosition mocks base method.
func (m *MockMovable) GetPosition() (pkg.Vector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosition")
	ret0, _ := ret[0].(pkg.Vector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosition indicates an expected call of GetPosition.
func (mr *MockMovableMockRecorder) GetPosition() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosition", reflect.TypeOf((*MockMovable)(nil).GetPosition))
}

// GetVelocity mocks base method.
func (m *MockMovable) GetVelocity() (pkg.Vector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVelocity")
	ret0, _ := ret[0].(pkg.Vector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVelocity indicates an expected call of GetVelocity.
func (mr *MockMovableMockRecorder) GetVelocity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVelocity", reflect.TypeOf((*MockMovable)(nil).GetVelocity))
}

// SetPosition mocks base method.
func (m *MockMovable) SetPosition(position pkg.Vector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPosition", position)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPosition indicates an expected call of SetPosition.
func (mr *MockMovableMockRecorder) SetPosition(position interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPosition", reflect.TypeOf((*MockMovable)(nil).SetPosition), position)
}
